// commands/packs/core/user/modding/template.js
import { EmbedBuilder } from 'discord.js';

export const command = {
    name: 'template',
    description: 'Get a basic Trailmakers mod template',
    permissionLevel: 'user',
    execute: async (interaction) => {
        const template = `
local initialized = false

function init()
    -- Log initialization
    tm.os.Log("Mod initialized!")
   
    -- Set up any required configurations
    initialized = true
   
    -- Set update frequency (60 times per second)
    tm.os.SetModTargetDeltaTime(1/60)
end

function update()
    -- Safety check to ensure initialization
    if not initialized then return end
   
    -- Add your update logic here
    -- Example: tm.os.Log("Update cycle: " .. tm.os.GetTime())
end

-- Register the init function to start the mod
init()`;

        const embed = new EmbedBuilder()
            .setColor('#00FF00')
            .setTitle('📝 Trailmakers Mod Template')
            .setDescription('Here\'s a basic template to get you started with Trailmakers modding!')
            .addFields({
                name: 'Template Details',
                value: [
                    '• Includes basic initialization',
                    '• 60 FPS update cycle',
                    '• Safety checks',
                    '• Basic structure for modding'
                ].join('\n')
            })
            .setFooter({ 
                text: `Generated by ${interaction.user.tag} • ${new Date().toISOString().split('T')[0]}`
            });

        await interaction.reply({
            embeds: [embed],
            content: `\`\`\`lua\n${template}\n\`\`\``,
            ephemeral: false
        });
    }
};