// config/constants.js
export const DEFAULT_SETTINGS = {
    warning_threshold: 4,
    warning_expire_days: 30,
    cooldowns: {
        createmod: 16,
        explaincode: 16,
        quote: 10,
        botd: 10,
        challenge: 10,
        joke: 10,
        randomvehicle: 10,
        trailroast: 16,
        block: 10,
        gamestats: 10,
        huelght: 10,
        logic: 10,
        moddiscord: 16,
        news: 16,
        template: 16
    }
};

export const VEHICLES = [
    "Helicopter", "Tank", "Submarine", "Space Shuttle", "Monster Truck",
    "Racing Car", "Amphibious Vehicle", "Hovercraft", "Flying Car",
    "Walking Mech", "Boat", "VTOL Aircraft", "Rover", "Dragster",
    "Stunt Plane", "Battle Robot", "Mining Vehicle", "Rescue Vehicle",
    "Blimp", "Jet Fighter", "Rocket-Powered Car", "Hydrofoil", "Snowmobile",
    "Armored Train", "Glider", "Spider Mech", "Cargo Truck", "Motorcycle",
    "Steam-Powered Vehicle", "Swamp Boat", "Drill Tank", "Caterpillar Track Vehicle",
    "Solar-Powered Car", "Magnetic Crane", "Giant Wheel Bike", "Tracked Digger",
    "Hover Bike", "Rocket Lander", "Skimmer Boat", "Wind-Powered Vehicle",
    "Electric Scooter", "Jetpack Suit", "Space Rover", "Flying Saucer", "Land Yacht",
    "Quadcopter", "Turbo Jet Boat", "Battering Ram Car", "Multi-Wheel Tank",
    "Balloon Vehicle", "Underwater Base Builder", "Floating Platform", 
    "Racing Hovercraft", "Tandem Helicopter", "Foldable Glider", "Rocket Chair",
    "Tunneling Machine", "Wheelie Bike", "Gravity-Defying Car", 
    "Grappling Hook Vehicle", "Suspension Bridge Builder", "Spring-Loaded Catapult",
    "High-Speed Snowplow", "Floating Mining Rig", "Rollerblade Vehicle",
    "Heavy-Lifting Crane", "One-Wheel Gyro Vehicle", "Tank Tread Walker",
    "Speedboat Submarine Hybrid", "Chain-Link Train", "Rocket-Propelled Glider",
    "Obstacle Course Vehicle", "Rescue Drone", "Heavy-Duty Dump Truck"
];

export const CHALLENGES = [
    "Build a vehicle that can drive upside down",
    "Create a transforming vehicle",
    "Build the smallest possible flying vehicle",
    "Make a vehicle that works both underwater and in the air",
    "Create a vehicle powered only by thrusters",
    "Build a walking vehicle with no wheels",
    "Make a vehicle that can climb vertical walls",
    "Create a self-balancing vehicle",
    "Build a vehicle that can flip itself over",
    "Create a vehicle that can grab and move objects",
    "Build a vehicle that can jump over large gaps",
    "Make a vehicle that can survive a crash from high altitude",
    "Build a vehicle that can tow another vehicle",
    "Create a vehicle that can launch projectiles",
    "Design a vehicle that can carry a fragile object safely",
    "Build a vehicle that can split into two separate vehicles",
    "Create a vehicle powered by wind turbines",
    "Build a submarine that can resurface quickly",
    "Design a vehicle that can navigate a maze",
    "Build a vehicle that can deliver cargo to a target",
    "Create a vehicle that can scale extreme slopes",
    "Make a vehicle that can leap off a ramp and land safely",
    "Build a fully amphibious vehicle that transitions seamlessly",
    "Create a vehicle that can attach to and lift another vehicle",
    "Design a vehicle to race across different terrains",
    "Build a vehicle that can catch and hold a falling object",
    "Make a vehicle powered by gears and pulleys only",
    "Create a vehicle that can refuel or repair another vehicle",
    "Design a solar-powered vehicle for night driving",
    "Build a vehicle with detachable booster rockets",
    "Create a vehicle that can balance on a single wheel",
    "Make a vehicle capable of launching itself from a cannon",
    "Build a vehicle that can avoid obstacles autonomously",
    "Design a vehicle with a spinning mechanism for propulsion",
    "Build a vehicle that can push heavy objects uphill",
    "Make a vehicle that can capture and release other vehicles",
    "Create a water vehicle that can survive in lava environments",
    "Design a high-speed vehicle that can stay in control on ice",
    "Build a chain reaction machine vehicle for fun challenges",
    "Create a synchronized dual-vehicle system for a race",
    "Make a single vehicle that can complete both land and water tracks",
    "Build a flying rescue vehicle that can carry another damaged vehicle",
    "Create a spring-powered jump vehicle for a vertical obstacle course",
    "Design a modular vehicle that can switch between forms mid-challenge",
    "Build a vehicle capable of staying stable in tornado simulations",
    "Create a grappling hook vehicle for extreme climbing challenges",
    "Make a single-rotor helicopter that can hover precisely",
    "Build a heavy-duty crane vehicle that can place objects in exact spots",
    "Create a racing boat that can temporarily glide in the air",
    "Make a fully enclosed vehicle that can survive underwater pressure",
    "Build a high-speed glider for narrow canyon flying",
    "Create a vehicle with wheels that can retract for different modes",
    "Design a drill-powered vehicle to break through destructible terrain",
    "Build a long-range glider that uses minimal fuel",
    "Make a tow truck vehicle that can drag another car through rough terrain"
];

export const WELCOME_MESSAGES = [
    "Welcome to the community! We're excited to have you here.",
    "{user}, welcome aboard! Let's make some awesome memories together.",
    "Glad to have you with us, {user}! The fun starts now.",
    "Hey {user}, welcome! Feel free to jump right in.",
    "A warm welcome to {user}! Let’s make this an adventure to remember.",
    "{user} has joined! Get ready to have a blast.",
    "Welcome to the crew! Ready to dive in, {user}?",
    "{user}, welcome to the community! Time to make some new friends.",
    "Happy to see you, {user}! Let’s make some magic happen.",
    "{user} is here! Let the good times roll.",
    "Welcome, {user}! We’ve been expecting you… *cue dramatic music*.",
    "Hey {user}, you’re officially one of us now. No refunds.",
    "Welcome to the chaos, {user}! Please leave your sanity at the door.",
    "{user} has arrived! Everyone, act natural.",
    "Greetings, {user}! Don’t worry, we’re only *slightly* weird here.",
    "{user}, welcome! Don’t touch the red button. Seriously.",
    "A wild {user} appears! Someone grab the Pokéball!",
    "Hey {user}, welcome! The snack table is over there. (Just kidding, there’s no snack table.)",
    "Welcome, {user}! Please keep your arms and legs inside the server at all times.",
    "Ahoy, {user}! The ship's a little chaotic, but it’s home.",
    "{user}, welcome to the crew! Your initiation starts now. Kidding… or am I?",
    "Welcome, {user}! We hope you brought snacks for everyone.",
    "{user} joined the party! Time to roll for initiative.",
    "Welcome, {user}! Let’s pretend we’re normal for the first five minutes.",
    "{user} has entered the chat! Someone cue the applause.",
    "Welcome, {user}! You’re not late—we were just waiting for you to get started.",
    "{user}, welcome! Warning: excessive puns ahead.",
    "Welcome to the server, {user}! The sarcasm is complimentary.",
    "{user} has joined! Now 20% cooler.",
    "Welcome, {user}! Just remember, we’re all here to have fun… mostly.",
    "Welcome, {user}! Your inventory is empty, but your potential isn’t.",
    "A new hero joins the quest! Welcome, {user}!",
    "Welcome, {user}! Your journey begins now.",
    "Welcome, {user}! Don’t worry, the respawn timer isn’t too long here.",
    "Welcome to the family, {user}! We’re all a little weird here.",
    "Hey {user}, the more the merrier! Let’s make this server pop.",
    "Welcome, {user}! The Wi-Fi password is… oh wait, wrong place.",
    "{user} has arrived! Let’s pretend we know what we’re doing.",
    "Hey {user}, glad you’re here! Don’t worry, we’re mostly friendly.",
    "Welcome, {user}! Hope you like bad jokes and good company.",
    "Hey {user}, new friends and good vibes await you here!",
    "Welcome, {user}! We promise not to steal your memes… much.",
    "{user} joined! Let’s show them how awesome this place is.",
    "Hey {user}, welcome! Now the party can really get started.",
];


export const FILTERED_TERMS = {
    explicit: [
        "fuck", "shit", "asshole", "whore", "nigger", "kike", "wetback", "beaner", 
        "homo", "fag", "slut", "cunt", "twat", "pussy", "dick", "bitch", "titties", 
        "boobs", "penis", "vagina", "bastard", "goddamn", "hell", "damnation", 
        "bollocks", "wanker", "cocksucker", "motherfucker", "son of a bitch", 
        "crap", "feck", "knob", "bellend", "sod", "bugger", "piss", "pissed", 
        "wank", "schlong", "wang", "snatch", "poon", "jizz", "spunk", "gash", 
        "muff", "labia", "clit", "clitoris", "pube", "pubes", "nutsack", 
        "scrotum", "testicle", "testicles", "boner", "hard-on", "erection", "sex", 
        "fucking", "fucked", "fucker", "fuckers", "molest", "raped", "raping", 
        "rape", "sexual harassment", "porn", "porno", "prostitute", "bros before hoes", 
        "pimp", "stripper", "strip club", "hooker", "jack off", "jerk off", "beating off", 
        "chokin' the chicken", "spank the monkey"
    ],
    suspicious: [
        "racist", "bigoted", "violent", 
        "homophobic", "transphobic", "xenophobic", "ageist", "sizeist", 
        "sexist", "misogynistic", "misogynist", "threat", "threaten", "kill", 
        "murder", "die", "death", "suicide", "self-harm", "cutting", "blood", 
        "gore", "torture", "abuse", "incest", "bestiality", "pedophile", "pedophilia", 
        "child abuse", "domestic abuse", "animal cruelty", "trolling", "doxxing", 
        "dogpiling", "brigading", "raiding", "mental breakdown", 
        "insane", "psychotic", "crazy", "stalker", "creepy", "stalk", "harass", 
        "harassment", "bully", "terrorist", "terrorism", "bomb", "shoot", "shooter", 
        "shooting", "massacre", "genocide", "holocaust", "lynch", "lynching", 
        "mutilate", "decapitate", "behead", "neckbeard", "incel", 
        "male tears", "cuck", "cuckservative", "libtard", "snowflake", "sjw", 
        "microaggression", 
        "cultural appropriation", "mansplaining", "gaslighting", "fake news", 
        "alternative facts", "post-truth", "conspiracy theory", "echo chamber", 
        "false balance", "race baiting", "dog whistle", 
        "dehumanizing", "blaming the victim", "tone policing", "whataboutism", 
        "derailing", "sealioning", "concern trolling", "slut shaming", "rape culture", 
        "manspreading", "manterruption", "hepeating", "toxic masculinity", 
        "patriarchy", "white supremacy", "black supremacy", "nationalism", "fascism", 
        "nazi", "neo-nazi", "heil hitler", "hitler", "kkk", "klan", "grand wizard", 
        "imperial wizard", "alright", "pepe", "kek", "REEEEEE", "cope", "jew", 
        "zionist", "israel", "palestine", "gaza", "holocaust", "commie", "socialist", 
        "capitalism", "anarchy", "race war", "boogaloo", "faggots", "homosexuality", 
        "nigga", "niggaz", "darkie", "coon", "jiggaboo", "negro", "blacken", 
        "blackface"
    ]
};