// commands/packs/trailmakers/user/utilities/template.js
import { EmbedBuilder } from 'discord.js';

export const command = {
    name: 'template',
    description: 'Get a basic Trailmakers mod template',
    permissionLevel: 'user',
    execute: async (interaction) => {
        const template = `
-- Log mod started
tm.os.Log("Mod started!")
   
-- Set update frequency (60 times per second)
tm.os.SetModTargetDeltaTime(1/60)

function update()
    -- Something that happens every frame
end`;

        const embed = new EmbedBuilder()
            .setColor('#00FF00')
            .setTitle('📝 Trailmakers Mod Template')
            .setDescription('Here\'s a basic template to get you started with Trailmakers modding!')
            .addFields({
                name: 'Template Details',
                value: [
                    '• 60 FPS update cycle',
                    '• Basic structure for modding'
                ].join('\n')
            })
            .setFooter({ 
                text: `Generated by ${interaction.user.tag} • ${new Date().toISOString().split('T')[0]}`
            });

        await interaction.reply({
            embeds: [embed],
            content: `\`\`\`lua\n${template}\n\`\`\``,
            ephemeral: false
        });
    }
};